### ISSUE TITLE
using "das" more than 1 time is not highlighting the code as expected 

### ISSUE THREAD

**Issue by prafful-panwar** [kevincobain2000/medium-code-highlight#1]
dasdas
sadas
asdas
das
d
asdas
das

<img width="773" alt="image" src="https://user-images.githubusercontent.com/4869823/150630393-b320e1c6-6477-4c07-b625-59d922c3911b.png">

**Comment by kevincobain2000** [comment]
The tool uses highlight.js under the hood.
